/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pokemon;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import outils.SingletonJDBC;

/**
 *
 * @author jmessaou
 */
public class Accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Accueil.class.getName());
    
    // --- VARIABLES LOBBY ---
    private int connectedPlayers = 0;
    private String myPseudo = null; 
    private java.util.Map<String, String> playerRoles = new java.util.HashMap<>(); 
    private boolean rolesAssigned = false;
    private String myRole = null; 
    private static final String[] ROLES = {"Dresseur", "Drascore", "Libegon"};
    private java.util.List<String> connectedPlayerNames = new java.util.ArrayList<>();
    private static final int MAX_PLAYERS = 3;

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        
        // Nettoyage au démarrage (Optionnel, dépend de ta stratégie)
        // nettoyerConnexionsBDD(); 
        
        initComponents();  
        
        // --- IMAGE DE FOND ---
        pack(); 
        javax.swing.JLabel background = new javax.swing.JLabel();
        try {
            java.net.URL imgURL = getClass().getResource("/resources/Foret_de_Rambouillet.png");
            if (imgURL != null) {
                ImageIcon icon = new ImageIcon(imgURL);
                this.setSize(icon.getIconWidth(), icon.getIconHeight());
                background.setIcon(icon);
            }
        } catch (Exception e) { System.err.println("Image fond non trouvée"); }
        
        this.setLocationRelativeTo(null);
        background.setBounds(0, 0, this.getWidth(), this.getHeight());
        this.getLayeredPane().add(background, new Integer(Integer.MIN_VALUE));
        ((javax.swing.JPanel)this.getContentPane()).setOpaque(false);
        
        // Redimensionnement dynamique du fond
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                background.setSize(getWidth(), getHeight());
            }
        });

        // --- SETUP LOGIQUE ---
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        if (jProgressBar1 != null) jProgressBar1.setMaximum(MAX_PLAYERS);
        
        demarrerActualisationAutomatique();
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (myPseudo != null) retirerConnexionBDD(myPseudo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Veuillez attendre que tous les joueurs se connectent...");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de joueurs connectés : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pseudo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mot de passe");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Connectez-vous à l'application...");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Entrez...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // --- LOGIQUE METIER DU LOBBY ---

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String pseudo = jTextField1.getText().trim();
        String mdp = jTextField2.getText().trim();

        if (pseudo.isEmpty() || mdp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Champs vides !");
            return;
        }

        if (pseudoExiste(pseudo)) {
            if (mdpCorrect(pseudo, mdp)) {
                
                // Vérifier si déjà connecté
                if (estDejaConnecteBDD(pseudo)) {
                    JOptionPane.showMessageDialog(null, "Déjà connecté ailleurs !");
                    return;
                }

                // Connexion réussie
                myPseudo = pseudo;
                ajouterConnexionBDD(pseudo);
                
                connectedPlayers = compterConnexionsBDD();
                actualiserListeJoueursDepuisBDD();
                updatePlayerCount(connectedPlayers);

                // UI Update
                jTextField1.setEnabled(false);
                jTextField2.setEnabled(false);
                jButton1.setEnabled(false);
                
                JOptionPane.showMessageDialog(null, "Bienvenue " + pseudo + " ! En attente des autres joueurs...");

            } else {
                JOptionPane.showMessageDialog(null, "Mot de passe incorrect.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pseudo introuvable.");
        }
    }

    private void demarrerActualisationAutomatique() {
        javax.swing.Timer timer = new javax.swing.Timer(3000, e -> {
            if (connectedPlayers < MAX_PLAYERS || !rolesAssigned) {
                int nouveauCompte = compterConnexionsBDD();
                if (nouveauCompte != connectedPlayers) {
                    connectedPlayers = nouveauCompte;
                    updatePlayerCount(connectedPlayers);
                    actualiserListeJoueursDepuisBDD();
                    checkAndAssignRoles();
                }
            }
        });
        timer.start();
    }

    private void checkAndAssignRoles() {
        if (connectedPlayers == MAX_PLAYERS && !rolesAssigned) {
            if (!areRolesAlreadyAssignedInDB()) {
                assignRoles(); // Je suis le premier à détecter, j'assigne
            } else {
                retrieveRolesFromDB(); // Les rôles sont là, je les récupère
            }
            
            // Une fois les rôles connus, on prépare le lancement
            if (myRole != null) {
                startGame();
            } else {
                // Petite attente pour la propagation BDD
                javax.swing.Timer t = new javax.swing.Timer(1000, e -> {
                    retrieveMyRoleFromDB();
                    if(myRole != null) startGame();
                });
                t.setRepeats(false); t.start();
            }
        }
    }

    private void assignRoles() {
        if (rolesAssigned) return;
        java.util.List<String> rolesToAssign = new java.util.ArrayList<>(java.util.Arrays.asList(ROLES));
        java.util.Collections.shuffle(rolesToAssign);

        for (int i = 0; i < connectedPlayerNames.size(); i++) {
            String p = connectedPlayerNames.get(i);
            String r = rolesToAssign.get(i);
            
            // Mise à jour BDD
            mettreAJourRoleBDD(p, r);
            
            if (p.equals(myPseudo)) myRole = r;
        }
        rolesAssigned = true;
    }

    // --- LE POINT CRUCIAL : LANCEMENT DU JEU ---
    private void startGame() {
        // C'est ICI que ça change : on passe le pseudo ET le rôle
        JOptionPane.showMessageDialog(this, "La partie commence ! Vous êtes : " + myRole);
        
        this.setVisible(false);
        // On appelle le constructeur correct de FenetreDeJeu
        FenetreDeJeu fenetreJeu = new FenetreDeJeu(myPseudo, myRole);
        fenetreJeu.setVisible(true);
    }

    // --- REQUETES BDD ---

    private boolean pseudoExiste(String pseudo) {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT COUNT(*) FROM joueurs WHERE pseudo = ?");
            p.setString(1, pseudo); ResultSet r = p.executeQuery();
            if(r.next()) return r.getInt(1) > 0;
        } catch (Exception e) {} return false;
    }

    private boolean mdpCorrect(String pseudo, String mdp) {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT motDePasse FROM joueurs WHERE pseudo = ?");
            p.setString(1, pseudo); ResultSet r = p.executeQuery();
            if(r.next()) return mdp.equals(r.getString("motDePasse"));
        } catch (Exception e) {} return false;
    }

    private void ajouterConnexionBDD(String pseudo) {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("INSERT INTO connexions_en_cours (pseudo) VALUES (?) ON DUPLICATE KEY UPDATE date_connexion = NOW(), statut = 'EN_LIGNE'");
            p.setString(1, pseudo); p.executeUpdate(); p.close();
        } catch (Exception e) {}
    }

    private void retirerConnexionBDD(String pseudo) {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("DELETE FROM connexions_en_cours WHERE pseudo = ?");
            p.setString(1, pseudo); p.executeUpdate(); p.close();
        } catch (Exception e) {}
    }

    private int compterConnexionsBDD() {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT COUNT(*) as nb FROM connexions_en_cours WHERE statut = 'EN_LIGNE'");
            ResultSet r = p.executeQuery();
            if(r.next()) return r.getInt("nb");
        } catch (Exception e) {} return 0;
    }

    private boolean estDejaConnecteBDD(String pseudo) {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT COUNT(*) FROM connexions_en_cours WHERE pseudo = ? AND statut = 'EN_LIGNE'");
            p.setString(1, pseudo); ResultSet r = p.executeQuery();
            if(r.next()) return r.getInt(1) > 0;
        } catch (Exception e) {} return false;
    }

    private void actualiserListeJoueursDepuisBDD() {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT pseudo FROM connexions_en_cours WHERE statut = 'EN_LIGNE'");
            ResultSet r = p.executeQuery();
            connectedPlayerNames.clear();
            while(r.next()) connectedPlayerNames.add(r.getString("pseudo"));
            p.close();
        } catch (Exception e) {}
    }

    private boolean areRolesAlreadyAssignedInDB() {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT COUNT(*) FROM joueurs WHERE role IS NOT NULL AND role != 'none' AND role != ''");
            ResultSet r = p.executeQuery();
            if(r.next()) return r.getInt(1) >= MAX_PLAYERS;
        } catch (Exception e) {} return false;
    }

    private void retrieveRolesFromDB() {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT pseudo, role FROM joueurs WHERE role IS NOT NULL");
            ResultSet r = p.executeQuery();
            while(r.next()) if(r.getString("pseudo").equals(myPseudo)) myRole = r.getString("role");
            rolesAssigned = true;
        } catch (Exception e) {}
    }
    
    private void retrieveMyRoleFromDB() {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("SELECT role FROM joueurs WHERE pseudo = ?");
            p.setString(1, myPseudo); ResultSet r = p.executeQuery();
            if(r.next()) myRole = r.getString("role");
        } catch (Exception e) {}
    }

    private void mettreAJourRoleBDD(String pseudo, String role) {
        try {
            Connection c = SingletonJDBC.getInstance().getConnection();
            PreparedStatement p = c.prepareStatement("UPDATE joueurs SET role = ? WHERE pseudo = ?");
            p.setString(1, role); p.setString(2, pseudo); p.executeUpdate(); p.close();
        } catch (Exception e) {}
    }

    public void updatePlayerCount(int count) {
        this.connectedPlayers = count;
        jLabel6.setText(String.valueOf(count));
        if (jProgressBar1 != null) {
            jProgressBar1.setValue(count);
            // Couleurs
            float p = (float) count / MAX_PLAYERS;
            if (p < 0.5) jProgressBar1.setForeground(java.awt.Color.RED);
            else if (p < 1.0) jProgressBar1.setForeground(java.awt.Color.ORANGE);
            else jProgressBar1.setForeground(java.awt.Color.GREEN);
        }
        if (count >= MAX_PLAYERS) {
            jLabel2.setText("Lobby complet ! Lancement...");
            jLabel2.setForeground(java.awt.Color.GREEN);
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) { logger.log(java.util.logging.Level.SEVERE, null, ex); }
        java.awt.EventQueue.invokeLater(() -> new Accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}